# Generated by Django 3.2.3 on 2021-06-14 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Kanji Character')),
                ('primary', models.CharField(max_length=50, verbose_name='Primary meaning')),
                ('level', models.PositiveIntegerField(verbose_name='Level')),
            ],
            options={
                'verbose_name': 'Kanji',
                'verbose_name_plural': 'Kanji',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Word')),
                ('primary', models.CharField(max_length=50, verbose_name='Primary meaning')),
                ('level', models.PositiveIntegerField(verbose_name='Level')),
                ('composition', models.ManyToManyField(to='api.Kanji')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Type')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Reading')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Alternative')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative', to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progress')),
                ('next_step', models.DateTimeField(default=None, null=True, verbose_name='Next step')),
                ('unlocked_date', models.DateTimeField(auto_now=True, verbose_name='When unlocked')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_progress', to='api.user')),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserKanjiProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Progress')),
                ('next_step', models.DateTimeField(default=None, null=True, verbose_name='Next step')),
                ('unlocked_date', models.DateTimeField(auto_now=True, verbose_name='When unlocked')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kanji')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_progress', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jap', models.TextField(verbose_name='Japanese sentence')),
                ('eng', models.TextField(verbose_name='English sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence', to='api.word')),
            ],
        ),
        migrations.CreateModel(
            name='Onyomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Chinese reading')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onyomi', to='api.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Kunyomi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Japanese reading')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kunyomi', to='api.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='KanjiAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kanji Alternative meaning')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative', to='api.kanji')),
            ],
        ),
    ]
