# Generated by Django 3.2.3 on 2021-06-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kanji',
            old_name='name',
            new_name='kanji',
        ),
        migrations.RenameField(
            model_name='kanjialternative',
            old_name='name',
            new_name='alternative',
        ),
        migrations.RenameField(
            model_name='kunyomi',
            old_name='name',
            new_name='kunyomi',
        ),
        migrations.RenameField(
            model_name='onyomi',
            old_name='name',
            new_name='onyomi',
        ),
        migrations.AlterField(
            model_name='word',
            name='composition',
            field=models.ManyToManyField(blank=True, to='api.Kanji'),
        ),
    ]
