# Generated by Django 3.2.3 on 2021-06-20 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210620_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='name',
            new_name='word',
        ),
        migrations.RenameField(
            model_name='wordalternative',
            old_name='name',
            new_name='alternative',
        ),
        migrations.RenameField(
            model_name='wordreading',
            old_name='name',
            new_name='reading',
        ),
        migrations.RenameField(
            model_name='wordtype',
            old_name='name',
            new_name='type',
        ),
    ]
