# Generated by Django 3.2.3 on 2021-06-25 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_auto_20210621_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkanjiprogress',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwordprogress',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
