# Generated by Django 3.2.3 on 2021-06-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210625_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanjialternative',
            name='kanji',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='api.kanji'),
        ),
    ]
