# Generated by Django 3.2.3 on 2021-06-25 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_kanjialternative_kanji'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanjialternative',
            options={'verbose_name': 'Kanji Alternative', 'verbose_name_plural': 'Kanji Alternatives'},
        ),
        migrations.AlterModelOptions(
            name='kunyomi',
            options={'verbose_name': 'Kanji Kunyomi', 'verbose_name_plural': 'Kanji Kunyomi'},
        ),
        migrations.AlterModelOptions(
            name='onyomi',
            options={'verbose_name': 'Kanji Onyomi', 'verbose_name_plural': 'Kanji Onyomi'},
        ),
        migrations.AlterModelOptions(
            name='sentence',
            options={'verbose_name': 'Sentence', 'verbose_name_plural': 'Sentences'},
        ),
        migrations.AlterModelOptions(
            name='wordalternative',
            options={'verbose_name': 'Word Alternative', 'verbose_name_plural': 'Word Alternatives'},
        ),
        migrations.AlterModelOptions(
            name='wordreading',
            options={'verbose_name': 'Word Reading', 'verbose_name_plural': 'Word Readings'},
        ),
        migrations.AlterModelOptions(
            name='wordtype',
            options={'verbose_name': 'Word Type', 'verbose_name_plural': 'Word Types'},
        ),
        migrations.AlterModelTable(
            name='kanji',
            table='kanji',
        ),
        migrations.AlterModelTable(
            name='kanjialternative',
            table='kanji_alternatives',
        ),
        migrations.AlterModelTable(
            name='kunyomi',
            table='kanji_kunyomi',
        ),
        migrations.AlterModelTable(
            name='onyomi',
            table='kanji_onyomi',
        ),
        migrations.AlterModelTable(
            name='sentence',
            table='sentences',
        ),
        migrations.AlterModelTable(
            name='word',
            table='words',
        ),
        migrations.AlterModelTable(
            name='wordalternative',
            table='word_alternatives',
        ),
        migrations.AlterModelTable(
            name='wordreading',
            table='word_readings',
        ),
        migrations.AlterModelTable(
            name='wordtype',
            table='word_types',
        ),
    ]
