# Generated by Django 3.2.3 on 2021-06-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210625_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userkanjiprogress',
            options={'verbose_name': 'User Kanji Progress', 'verbose_name_plural': 'User Kanji Progress'},
        ),
        migrations.AlterModelOptions(
            name='userwordprogress',
            options={'verbose_name': 'User Word Progress', 'verbose_name_plural': 'User Word Progress'},
        ),
        migrations.AlterModelTable(
            name='userkanjiprogress',
            table='user_kanji_progress',
        ),
        migrations.AlterModelTable(
            name='userwordprogress',
            table='user_word_progress',
        ),
    ]
