# Generated by Django 3.2.3 on 2021-06-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Kanji Character')),
                ('primary', models.CharField(max_length=50, verbose_name='Primary meaning')),
                ('progress', models.CharField(max_length=15, verbose_name='Learning step')),
                ('level', models.IntegerField(verbose_name='Levels from wanikani')),
            ],
            options={
                'verbose_name': 'Kanji',
                'ordering': ['-level'],
            },
        ),
    ]
