# Generated by Django 3.2.3 on 2021-06-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanji',
            options={'ordering': ['-level'], 'verbose_name': 'Kanji', 'verbose_name_plural': 'Kanji'},
        ),
        migrations.RemoveField(
            model_name='kanji',
            name='progress',
        ),
        migrations.AlterField(
            model_name='kanji',
            name='level',
            field=models.PositiveIntegerField(verbose_name='Levels from wanikani'),
        ),
        migrations.CreateModel(
            name='KanjiAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Kanji Alternative meaning')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji', to='kanji.kanji')),
            ],
        ),
    ]
