# Generated by Django 3.2.3 on 2021-06-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0003_auto_20210610_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanji',
            name='level',
            field=models.PositiveIntegerField(verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='kanji',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='Kanji Character'),
        ),
    ]
