# Generated by Django 3.2.3 on 2021-06-14 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('words', '0003_alter_word_composition'),
        ('kanji', '0004_auto_20210612_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.CreateModel(
            name='UserWordProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(verbose_name='Progress')),
                ('next_step', models.DateTimeField(verbose_name='Next step')),
                ('unlocked_date', models.DateTimeField(verbose_name='When unlocked')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words_progress', to='users.user')),
                ('words', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='UserKanjiProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.PositiveIntegerField(verbose_name='Progress')),
                ('next_step', models.DateTimeField(verbose_name='Next step')),
                ('unlocked_date', models.DateTimeField(verbose_name='When unlocked')),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanji.kanji')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kanji_progress', to='users.user')),
            ],
        ),
    ]
