version: "3.9"

services:
  postgres:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    logging:
      driver: 'gelf'
      options:
        gelf-address: 'udp://localhost:12201'
        tag: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: srv_dba
      APP_DB_USER: docker
      APP_DB_PASS: docker
    networks:
      - srvnw
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./scripts/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh

volumes:
  pgdata:
    driver: local
  esdata:
    driver: local
  mongodata:
    driver: local

networks:
  srvnw:
    driver: bridge


  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
  #   environment:
  #     - http.host=0.0.0.0
  #     - transport.host=localhost
  #     - network.host=0.0.0.0
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1g
  #   networks:
  #     - srvnw
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data
  # # Elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/6.x/docker.html

  # mongo:
  #   image: mongo:4.2
  #   restart: always
  #   networks:
  #     - srvnw
  #   volumes:
  #     - mongodata:/data/db

  # # Graylog: https://hub.docker.com/r/graylog/graylog/
  # graylog:
  #   image: graylog/graylog:4.0
  #   environment:
  #     # CHANGE ME (must be at least 16 characters)!
  #     - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
  #     # Password: admin
  #     - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
  #     - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
  #   entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
  #   networks:
  #     - srvnw
  #   links:
  #     - mongo
  #     - elasticsearch
  #   depends_on:
  #     - mongo
  #     - elasticsearch
  #   ports:
  #     # Graylog web interface and REST API
  #     - 9000:9000
  #     # Syslog TCP
  #     - 1514:1514
  #     # Syslog UDP
  #     - 1514:1514/udp
  #     # GELF TCP
  #     - 12201:12201
  #     # GELF UDP
  #     - 12201:12201/udp
  #   restart: always

