// Code generated by MockGen. DO NOT EDIT.
// Source: ./api/api_kanji.go

// Package mock_api is a generated GoMock package.
package mock_api

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/tomazis/kioku/server/srv-frontend-api/internal/models/kanji"
)

// MockRepoKanji is a mock of RepoKanji interface.
type MockRepoKanji struct {
	ctrl     *gomock.Controller
	recorder *MockRepoKanjiMockRecorder
}

// MockRepoKanjiMockRecorder is the mock recorder for MockRepoKanji.
type MockRepoKanjiMockRecorder struct {
	mock *MockRepoKanji
}

// NewMockRepoKanji creates a new mock instance.
func NewMockRepoKanji(ctrl *gomock.Controller) *MockRepoKanji {
	mock := &MockRepoKanji{ctrl: ctrl}
	mock.recorder = &MockRepoKanjiMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoKanji) EXPECT() *MockRepoKanjiMockRecorder {
	return m.recorder
}

// GetKanji mocks base method.
func (m *MockRepoKanji) GetKanji(ctx context.Context, kanjiID uint64) (*models.Kanji, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKanji", ctx, kanjiID)
	ret0, _ := ret[0].(*models.Kanji)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKanji indicates an expected call of GetKanji.
func (mr *MockRepoKanjiMockRecorder) GetKanji(ctx, kanjiID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKanji", reflect.TypeOf((*MockRepoKanji)(nil).GetKanji), ctx, kanjiID)
}

// ListKanji mocks base method.
func (m *MockRepoKanji) ListKanji(ctx context.Context, level uint32) ([]*models.Kanji, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListKanji", ctx, level)
	ret0, _ := ret[0].([]*models.Kanji)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListKanji indicates an expected call of ListKanji.
func (mr *MockRepoKanjiMockRecorder) ListKanji(ctx, level interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListKanji", reflect.TypeOf((*MockRepoKanji)(nil).ListKanji), ctx, level)
}
