// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.1
// source: kioku/srv-dba/v1/srv-dba-word.proto

package srv_dba

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SentenceTranslation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language    uint32 `protobuf:"varint,1,opt,name=language,proto3" json:"language,omitempty"`
	Translation string `protobuf:"bytes,2,opt,name=translation,proto3" json:"translation,omitempty"`
}

func (x *SentenceTranslation) Reset() {
	*x = SentenceTranslation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SentenceTranslation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SentenceTranslation) ProtoMessage() {}

func (x *SentenceTranslation) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SentenceTranslation.ProtoReflect.Descriptor instead.
func (*SentenceTranslation) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{0}
}

func (x *SentenceTranslation) GetLanguage() uint32 {
	if x != nil {
		return x.Language
	}
	return 0
}

func (x *SentenceTranslation) GetTranslation() string {
	if x != nil {
		return x.Translation
	}
	return ""
}

type Sentence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Origin       string                 `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	Translations []*SentenceTranslation `protobuf:"bytes,2,rep,name=translations,proto3" json:"translations,omitempty"`
}

func (x *Sentence) Reset() {
	*x = Sentence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sentence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sentence) ProtoMessage() {}

func (x *Sentence) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sentence.ProtoReflect.Descriptor instead.
func (*Sentence) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{1}
}

func (x *Sentence) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *Sentence) GetTranslations() []*SentenceTranslation {
	if x != nil {
		return x.Translations
	}
	return nil
}

type Word struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           uint64      `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Word         string      `protobuf:"bytes,2,opt,name=word,proto3" json:"word,omitempty"`
	Primary      string      `protobuf:"bytes,3,opt,name=primary,proto3" json:"primary,omitempty"`
	Level        uint32      `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Composition  []*Kanji    `protobuf:"bytes,5,rep,name=composition,proto3" json:"composition,omitempty"`
	Alternatives []string    `protobuf:"bytes,6,rep,name=alternatives,proto3" json:"alternatives,omitempty"`
	Readings     []string    `protobuf:"bytes,7,rep,name=readings,proto3" json:"readings,omitempty"`
	Types        []string    `protobuf:"bytes,8,rep,name=types,proto3" json:"types,omitempty"`
	Sentences    []*Sentence `protobuf:"bytes,9,rep,name=sentences,proto3" json:"sentences,omitempty"`
}

func (x *Word) Reset() {
	*x = Word{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Word) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Word) ProtoMessage() {}

func (x *Word) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Word.ProtoReflect.Descriptor instead.
func (*Word) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{2}
}

func (x *Word) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Word) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *Word) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *Word) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Word) GetComposition() []*Kanji {
	if x != nil {
		return x.Composition
	}
	return nil
}

func (x *Word) GetAlternatives() []string {
	if x != nil {
		return x.Alternatives
	}
	return nil
}

func (x *Word) GetReadings() []string {
	if x != nil {
		return x.Readings
	}
	return nil
}

func (x *Word) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *Word) GetSentences() []*Sentence {
	if x != nil {
		return x.Sentences
	}
	return nil
}

type GetWordByIdV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordId uint64 `protobuf:"varint,1,opt,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
}

func (x *GetWordByIdV1Request) Reset() {
	*x = GetWordByIdV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWordByIdV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordByIdV1Request) ProtoMessage() {}

func (x *GetWordByIdV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordByIdV1Request.ProtoReflect.Descriptor instead.
func (*GetWordByIdV1Request) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{3}
}

func (x *GetWordByIdV1Request) GetWordId() uint64 {
	if x != nil {
		return x.WordId
	}
	return 0
}

type GetWordByIdV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word *Word `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
}

func (x *GetWordByIdV1Response) Reset() {
	*x = GetWordByIdV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetWordByIdV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWordByIdV1Response) ProtoMessage() {}

func (x *GetWordByIdV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWordByIdV1Response.ProtoReflect.Descriptor instead.
func (*GetWordByIdV1Response) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{4}
}

func (x *GetWordByIdV1Response) GetWord() *Word {
	if x != nil {
		return x.Word
	}
	return nil
}

type ListWordsByLevelV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Level  uint32 `protobuf:"varint,1,opt,name=level,proto3" json:"level,omitempty"`
	Limit  uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListWordsByLevelV1Request) Reset() {
	*x = ListWordsByLevelV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWordsByLevelV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordsByLevelV1Request) ProtoMessage() {}

func (x *ListWordsByLevelV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordsByLevelV1Request.ProtoReflect.Descriptor instead.
func (*ListWordsByLevelV1Request) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{5}
}

func (x *ListWordsByLevelV1Request) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *ListWordsByLevelV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWordsByLevelV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWordsByKanjiV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KanjiId uint64 `protobuf:"varint,1,opt,name=kanji_id,json=kanjiId,proto3" json:"kanji_id,omitempty"`
	Limit   uint64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset  uint64 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListWordsByKanjiV1Request) Reset() {
	*x = ListWordsByKanjiV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWordsByKanjiV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordsByKanjiV1Request) ProtoMessage() {}

func (x *ListWordsByKanjiV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordsByKanjiV1Request.ProtoReflect.Descriptor instead.
func (*ListWordsByKanjiV1Request) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{6}
}

func (x *ListWordsByKanjiV1Request) GetKanjiId() uint64 {
	if x != nil {
		return x.KanjiId
	}
	return 0
}

func (x *ListWordsByKanjiV1Request) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListWordsByKanjiV1Request) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListWordsByIdsV1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WordId []uint64 `protobuf:"varint,1,rep,packed,name=word_id,json=wordId,proto3" json:"word_id,omitempty"`
}

func (x *ListWordsByIdsV1Request) Reset() {
	*x = ListWordsByIdsV1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWordsByIdsV1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordsByIdsV1Request) ProtoMessage() {}

func (x *ListWordsByIdsV1Request) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordsByIdsV1Request.ProtoReflect.Descriptor instead.
func (*ListWordsByIdsV1Request) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{7}
}

func (x *ListWordsByIdsV1Request) GetWordId() []uint64 {
	if x != nil {
		return x.WordId
	}
	return nil
}

type ListWordsV1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Words []*Word `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
}

func (x *ListWordsV1Response) Reset() {
	*x = ListWordsV1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListWordsV1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWordsV1Response) ProtoMessage() {}

func (x *ListWordsV1Response) ProtoReflect() protoreflect.Message {
	mi := &file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWordsV1Response.ProtoReflect.Descriptor instead.
func (*ListWordsV1Response) Descriptor() ([]byte, []int) {
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP(), []int{8}
}

func (x *ListWordsV1Response) GetWords() []*Word {
	if x != nil {
		return x.Words
	}
	return nil
}

var File_kioku_srv_dba_v1_srv_dba_word_proto protoreflect.FileDescriptor

var file_kioku_srv_dba_v1_srv_dba_word_proto_rawDesc = []byte{
	0x0a, 0x23, 0x6b, 0x69, 0x6f, 0x6b, 0x75, 0x2f, 0x73, 0x72, 0x76, 0x2d, 0x64, 0x62, 0x61, 0x2f,
	0x76, 0x31, 0x2f, 0x73, 0x72, 0x76, 0x2d, 0x64, 0x62, 0x61, 0x2d, 0x77, 0x6f, 0x72, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x6b, 0x69, 0x6f, 0x6b, 0x75, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2e, 0x73, 0x72, 0x76, 0x5f, 0x64, 0x62, 0x61, 0x2e, 0x76, 0x31, 0x1a, 0x17,
	0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x65, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x24, 0x6b, 0x69, 0x6f, 0x6b, 0x75, 0x2f, 0x73, 0x72,
	0x76, 0x2d, 0x64, 0x62, 0x61, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x72, 0x76, 0x2d, 0x64, 0x62, 0x61,
	0x2d, 0x6b, 0x61, 0x6e, 0x6a, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x53, 0x0a, 0x13,
	0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x12,
	0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x22, 0x74, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6f,
	0x72, 0x69, 0x67, 0x69, 0x6e, 0x12, 0x50, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x6c, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x6b, 0x69,
	0x6f, 0x6b, 0x75, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x72, 0x76, 0x5f, 0x64,
	0x62, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x6c, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xb3, 0x02, 0x0a, 0x04, 0x57, 0x6f, 0x72, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x77, 0x6f, 0x72, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x40, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x6b, 0x69, 0x6f, 0x6b,
	0x75, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x72, 0x76, 0x5f, 0x64, 0x62, 0x61,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x61, 0x6e, 0x6a, 0x69, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x6c,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65,
	0x61, 0x64, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x08, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x12, 0x3f, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x09, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x21, 0x2e, 0x6b, 0x69, 0x6f, 0x6b, 0x75, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73,
	0x72, 0x76, 0x5f, 0x64, 0x62, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x74, 0x65, 0x6e,
	0x63, 0x65, 0x52, 0x09, 0x73, 0x65, 0x6e, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x22, 0x38, 0x0a,
	0x14, 0x47, 0x65, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x42, 0x79, 0x49, 0x64, 0x56, 0x31, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x07, 0x77, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52,
	0x06, 0x77, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x57, 0x6f,
	0x72, 0x64, 0x42, 0x79, 0x49, 0x64, 0x56, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x6b, 0x69, 0x6f, 0x6b, 0x75, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x72,
	0x76, 0x5f, 0x64, 0x62, 0x61, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x22, 0x72, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x73,
	0x42, 0x79, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x42,
	0x07, 0xfa, 0x42, 0x04, 0x2a, 0x02, 0x20, 0x00, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12,
	0x1e, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x08,
	0xfa, 0x42, 0x05, 0x32, 0x03, 0x10, 0xe8, 0x07, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74, 0x22, 0x77, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x57,
	0x6f, 0x72, 0x64, 0x73, 0x42, 0x79, 0x4b, 0x61, 0x6e, 0x6a, 0x69, 0x56, 0x31, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x08, 0x6b, 0x61, 0x6e, 0x6a, 0x69, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x42, 0x07, 0xfa, 0x42, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52,
	0x07, 0x6b, 0x61, 0x6e, 0x6a, 0x69, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x42, 0x08, 0xfa, 0x42, 0x05, 0x32, 0x03, 0x10, 0xe8,
	0x07, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x66, 0x66, 0x73,
	0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x6f, 0x66, 0x66, 0x73, 0x65, 0x74,
	0x22, 0x40, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x79, 0x49,
	0x64, 0x73, 0x56, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x07, 0x77,
	0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x04, 0x42, 0x0c, 0xfa, 0x42,
	0x09, 0x92, 0x01, 0x06, 0x22, 0x04, 0x32, 0x02, 0x20, 0x00, 0x52, 0x06, 0x77, 0x6f, 0x72, 0x64,
	0x49, 0x64, 0x22, 0x4a, 0x0a, 0x13, 0x4c, 0x69, 0x73, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x56,
	0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x05, 0x77, 0x6f, 0x72,
	0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6b, 0x69, 0x6f, 0x6b, 0x75,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x73, 0x72, 0x76, 0x5f, 0x64, 0x62, 0x61, 0x2e,
	0x76, 0x31, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x42, 0x3d,
	0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x6f, 0x6d,
	0x61, 0x7a, 0x69, 0x73, 0x2f, 0x6b, 0x69, 0x6f, 0x6b, 0x75, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x73, 0x72, 0x76, 0x2d, 0x64, 0x62, 0x61, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x72,
	0x76, 0x2d, 0x64, 0x62, 0x61, 0x3b, 0x73, 0x72, 0x76, 0x5f, 0x64, 0x62, 0x61, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescOnce sync.Once
	file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescData = file_kioku_srv_dba_v1_srv_dba_word_proto_rawDesc
)

func file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescGZIP() []byte {
	file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescOnce.Do(func() {
		file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescData = protoimpl.X.CompressGZIP(file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescData)
	})
	return file_kioku_srv_dba_v1_srv_dba_word_proto_rawDescData
}

var file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_kioku_srv_dba_v1_srv_dba_word_proto_goTypes = []interface{}{
	(*SentenceTranslation)(nil),       // 0: kioku.server.srv_dba.v1.SentenceTranslation
	(*Sentence)(nil),                  // 1: kioku.server.srv_dba.v1.Sentence
	(*Word)(nil),                      // 2: kioku.server.srv_dba.v1.Word
	(*GetWordByIdV1Request)(nil),      // 3: kioku.server.srv_dba.v1.GetWordByIdV1Request
	(*GetWordByIdV1Response)(nil),     // 4: kioku.server.srv_dba.v1.GetWordByIdV1Response
	(*ListWordsByLevelV1Request)(nil), // 5: kioku.server.srv_dba.v1.ListWordsByLevelV1Request
	(*ListWordsByKanjiV1Request)(nil), // 6: kioku.server.srv_dba.v1.ListWordsByKanjiV1Request
	(*ListWordsByIdsV1Request)(nil),   // 7: kioku.server.srv_dba.v1.ListWordsByIdsV1Request
	(*ListWordsV1Response)(nil),       // 8: kioku.server.srv_dba.v1.ListWordsV1Response
	(*Kanji)(nil),                     // 9: kioku.server.srv_dba.v1.Kanji
}
var file_kioku_srv_dba_v1_srv_dba_word_proto_depIdxs = []int32{
	0, // 0: kioku.server.srv_dba.v1.Sentence.translations:type_name -> kioku.server.srv_dba.v1.SentenceTranslation
	9, // 1: kioku.server.srv_dba.v1.Word.composition:type_name -> kioku.server.srv_dba.v1.Kanji
	1, // 2: kioku.server.srv_dba.v1.Word.sentences:type_name -> kioku.server.srv_dba.v1.Sentence
	2, // 3: kioku.server.srv_dba.v1.GetWordByIdV1Response.word:type_name -> kioku.server.srv_dba.v1.Word
	2, // 4: kioku.server.srv_dba.v1.ListWordsV1Response.words:type_name -> kioku.server.srv_dba.v1.Word
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_kioku_srv_dba_v1_srv_dba_word_proto_init() }
func file_kioku_srv_dba_v1_srv_dba_word_proto_init() {
	if File_kioku_srv_dba_v1_srv_dba_word_proto != nil {
		return
	}
	file_kioku_srv_dba_v1_srv_dba_kanji_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SentenceTranslation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sentence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Word); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWordByIdV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetWordByIdV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWordsByLevelV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWordsByKanjiV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWordsByIdsV1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListWordsV1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_kioku_srv_dba_v1_srv_dba_word_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_kioku_srv_dba_v1_srv_dba_word_proto_goTypes,
		DependencyIndexes: file_kioku_srv_dba_v1_srv_dba_word_proto_depIdxs,
		MessageInfos:      file_kioku_srv_dba_v1_srv_dba_word_proto_msgTypes,
	}.Build()
	File_kioku_srv_dba_v1_srv_dba_word_proto = out.File
	file_kioku_srv_dba_v1_srv_dba_word_proto_rawDesc = nil
	file_kioku_srv_dba_v1_srv_dba_word_proto_goTypes = nil
	file_kioku_srv_dba_v1_srv_dba_word_proto_depIdxs = nil
}
