# Generated by Django 3.2.3 on 2021-06-11 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanji', '0004_auto_20210612_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Word')),
                ('primary', models.CharField(max_length=50, verbose_name='Primary meaning')),
                ('level', models.PositiveIntegerField(verbose_name='Level')),
                ('composition', models.ManyToManyField(null=True, to='kanji.Kanji')),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['-level'],
            },
        ),
        migrations.CreateModel(
            name='WordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Type')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Reading')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='WordAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Alternative')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternative', to='words.word')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jap', models.TextField(verbose_name='Japaneswe sentence')),
                ('eng', models.TextField(verbose_name='English sentence')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentence', to='words.word')),
            ],
        ),
    ]
