# Generated by Django 3.2.3 on 2021-06-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='jap',
            field=models.TextField(verbose_name='Japanese sentence'),
        ),
    ]
