# Generated by Django 3.2.3 on 2021-06-14 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanji', '0004_auto_20210612_0007'),
        ('words', '0002_alter_sentence_jap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='composition',
            field=models.ManyToManyField(to='kanji.Kanji'),
        ),
    ]
